version: '3.9'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mariadb-admin" , "-u", "root", '-proot', "ping", "-h", "localhost"]
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql
  print-status:
    image: busybox
    command: "echo '---\nSERVER RUNNING ON PORT 3306. USE CTRL+C TO TERMINATE.\n---'"    
    depends_on:
      mariadb:
        condition: service_healthy
volumes:
    db_data:
